<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:somaws" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:somaws">
<types>
<xsd:schema targetNamespace="urn:somaws"
>
 <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
 <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
</xsd:schema>
</types>
<message name="getSomaRequest">
  <part name="StringNumero" type="xsd:string" /></message>
<message name="getSomaResponse">
  <part name="return" type="xsd:int" /></message>
<portType name="somawsPortType">
  <operation name="getSoma">
    <documentation>Soma numeros passados por parametro separado por _</documentation>
    <input message="tns:getSomaRequest"/>
    <output message="tns:getSomaResponse"/>
  </operation>
</portType>
<binding name="somawsBinding" type="tns:somawsPortType">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="getSoma">
    <soap:operation soapAction="urn:somaws#getSoma" style="rpc"/>
    <input><soap:body use="encoded" namespace="urn:somaws" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
    <output><soap:body use="encoded" namespace="urn:somaws" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
  </operation>
</binding>
<service name="somaws">
  <port name="somawsPort" binding="tns:somawsBinding">
    <soap:address location="http://localhost/gestaosaudeumc/pages/test/somaws.php"/>
  </port>
</service>
</definitions>